version: '3.1'
services:
  RegisterLoginMicroService:
    image: micro.jar
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
#   depends_on:
#    - postgresqldb
#  postgresqldb:
#    image: postgres
#    restart: always
#    ports:
#      - "6666:6666"
#    environment:
 #     - POSTGRES_PASSWORD=root
  #    - POSTGRES_USER=postgres
   #   - POSTGRES_DB=techcareerairtiesgateway